# Generated by Django 5.2.4 on 2026-02-13 16:04

import django.db.models.deletion
import patients.storage
import patients.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_extend_profile_add_patient_profile'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('aadhar_id_proof', models.FileField(blank=True, help_text='Upload Aadhar card (image or PDF, max 5MB)', upload_to=patients.storage.patient_id_proof_path, validators=[patients.validators.validate_id_proof_file])),
                ('terms_accepted', models.BooleanField(default=False, help_text='User accepted Terms & Conditions')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('consent_store_data', models.BooleanField(default=False, help_text='Consent to store medical data')),
                ('consent_store_data_at', models.DateTimeField(blank=True, null=True)),
                ('consent_doctor_access', models.BooleanField(default=False, help_text='Consent for doctors to access medical records')),
                ('consent_doctor_access_at', models.DateTimeField(blank=True, null=True)),
                ('data_sharing_enabled', models.BooleanField(default=False, help_text='Allow anonymized data sharing for research')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_consent_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='India', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[patients.validators.validate_patient_age]),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, validators=[patients.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[patients.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=120, validators=[patients.validators.validate_full_name]),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'relationship'], name='patients_pr_user_id_9b3740_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['district', 'state'], name='patients_pr_distric_1f792c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['user', 'terms_accepted'], name='patients_pa_user_id_f0bbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['created_at'], name='patients_pa_created_bf99ad_idx'),
        ),
    ]
