# Generated by Django 4.2.28 on 2026-02-13 18:00

from django.db import migrations, models
import patients.storage


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_extend_profile_add_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo for ID card', null=True, upload_to=patients.storage.profile_photo_path),
        ),
    ]
