# Generated by Django 4.2.28 on 2026-02-13 18:28

from django.db import migrations, models
import patients.storage


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_add_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo for ID card (max 5MB, JPG/PNG)', null=True, upload_to=patients.storage.profile_photo_path),
        ),
    ]
