# Generated by Django 4.2.28 on 2026-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_add_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patient_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated unique patient identifier (HS-YYYY-XXXXXX)', max_length=20, null=True, unique=True),
        ),
    ]
