# Generated by Django 4.2.28 on 2026-02-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_profile_patient_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="patient_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Auto-generated unique patient identifier (HS-YYYY-XXXXXX)",
                max_length=20,
                unique=True,
            ),
        ),
    ]
