# Generated by Django 4.2.28 on 2026-02-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_alter_profile_patient_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="emergency_contact_number",
        ),
        migrations.DeleteModel(
            name="EmergencyContact",
        ),
    ]
