# Generated by Django 4.2.28 on 2026-02-10 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0002_user_active_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user_registration", "User Registration"),
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                            ("otp_sent", "OTP Sent"),
                            ("otp_verified", "OTP Verified"),
                            ("otp_failed", "OTP Failed"),
                            ("profile_created", "Profile Created"),
                            ("health_card_generated", "Health Card Generated"),
                            ("health_card_revoked", "Health Card Revoked"),
                            ("patient_record_accessed", "Patient Record Accessed"),
                            ("prescription_created", "Prescription Created"),
                            ("prescription_dispensed", "Prescription Dispensed"),
                            ("alert_generated", "Alert Generated"),
                            ("alert_acknowledged", "Alert Acknowledged"),
                            ("security_event", "Security Event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(blank=True, max_length=50)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("action", models.CharField(max_length=100)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="otp",
            new_name="accounts_ot_user_id_19c2c3_idx",
            old_name="accounts_otp_user_id_5115ac_idx",
        ),
        migrations.RenameIndex(
            model_name="session",
            new_name="accounts_se_user_id_c22015_idx",
            old_name="accounts_s_user_id_9d751c_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "event_type", "created_at"],
                name="accounts_au_user_id_fe5c41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="accounts_au_event_t_1d4237_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["severity", "created_at"], name="accounts_au_severit_6842ce_idx"
            ),
        ),
    ]
