# Generated by Django 5.2.4 on 2026-02-13 16:04

import accounts.storage
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_doctorprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Doctor Profile', 'verbose_name_plural': 'Doctor Profiles'},
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consultation fee in INR', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[accounts.validators.validate_doctor_age]),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='degree',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('MD', 'MD (Doctor of Medicine)'), ('MS', 'MS (Master of Surgery)'), ('DNB', 'DNB (Diplomate of National Board)'), ('BDS', 'BDS (Bachelor of Dental Surgery)'), ('BAMS', 'BAMS (Ayurvedic)'), ('BHMS', 'BHMS (Homeopathic)'), ('BUMS', 'BUMS (Unani)'), ('Other', 'Other')], default='MBBS', help_text='Primary medical degree', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='degree_certificate',
            field=models.FileField(blank=True, help_text='Medical degree certificate (PDF, max 10MB)', upload_to=accounts.storage.doctor_degree_path, validators=[accounts.validators.validate_medical_certificate]),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='degree_other',
            field=models.CharField(blank=True, help_text="Specify if 'Other' degree selected", max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0, help_text='Years of medical practice experience'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='government_id',
            field=models.FileField(blank=True, help_text='Government-issued ID (Aadhar/PAN/Passport, PDF/Image, max 5MB)', upload_to=accounts.storage.doctor_govt_id_path, validators=[accounts.validators.validate_medical_certificate]),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_certificate',
            field=models.FileField(blank=True, help_text='Medical license/registration certificate (PDF, max 10MB)', upload_to=accounts.storage.doctor_license_path, validators=[accounts.validators.validate_medical_certificate]),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_license',
            field=models.CharField(db_index=True, help_text='Medical registration number (e.g., MCI registration)', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['approval_status', 'created_at'], name='accounts_do_approva_81ed51_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['medical_license'], name='accounts_do_medical_85ff6a_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['specialization'], name='accounts_do_special_5ef898_idx'),
        ),
    ]
