# Generated by Django 4.2.28 on 2026-02-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_extend_profile_add_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
