# Generated by Django 4.2.28 on 2026-02-19 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_2fa_enabled_user_password_last_changed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("doctor", "Doctor"),
                    ("pharmacist", "Pharmacist"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PharmacistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        db_index=True,
                        help_text="Pharmacy Council Registration Number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        help_text="B.Pharm, M.Pharm, Pharm.D, etc.", max_length=100
                    ),
                ),
                ("pharmacy_name", models.CharField(blank=True, max_length=200)),
                (
                    "license_certificate",
                    models.FileField(
                        blank=True,
                        help_text="Pharmacy license certificate",
                        upload_to="pharmacist/licenses/",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_pharmacists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
