# Generated by Django 4.2.28 on 2026-02-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_role_pharmacistprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacistprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pharmacistprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
