# Generated by Django 4.2.29 on 2026-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_pharmacistprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("user_registration", "User Registration"),
                    ("user_login", "User Login"),
                    ("user_logout", "User Logout"),
                    ("otp_sent", "OTP Sent"),
                    ("otp_verified", "OTP Verified"),
                    ("otp_failed", "OTP Failed"),
                    ("profile_created", "Profile Created"),
                    ("health_card_generated", "Health Card Generated"),
                    ("health_card_revoked", "Health Card Revoked"),
                    ("patient_record_accessed", "Patient Record Accessed"),
                    ("prescription_created", "Prescription Created"),
                    ("prescription_dispensed", "Prescription Dispensed"),
                    ("prescription_validated", "Prescription Validated"),
                    ("alert_generated", "Alert Generated"),
                    ("alert_acknowledged", "Alert Acknowledged"),
                    ("security_event", "Security Event"),
                ],
                max_length=50,
            ),
        ),
    ]
