# Generated by Django 4.2.28 on 2026-02-10 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
        ("medical", "0002_doctorpatientaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("major", "Major"),
                            ("contraindicated", "Contraindicated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("generic_name", models.CharField(max_length=255)),
                ("drug_class", models.CharField(max_length=100)),
                ("therapeutic_category", models.CharField(max_length=100)),
                ("standard_dosages", models.JSONField(default=dict)),
                ("allergens", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qr_code_path", models.CharField(max_length=255)),
                ("security_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partially_dispensed", "Partially Dispensed"),
                            ("fully_dispensed", "Fully Dispensed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="medical.medicalrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionMedicine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("duration_days", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "dispense_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispensed", "Dispensed"),
                            ("unavailable", "Unavailable"),
                            ("patient_has", "Patient Already Has"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("dispensed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescriptions.medicine",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["name", "generic_name"], name="prescriptio_name_a771f7_idx"
            ),
        ),
        migrations.AddField(
            model_name="druginteraction",
            name="medicine_a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions_as_a",
                to="prescriptions.medicine",
            ),
        ),
        migrations.AddField(
            model_name="druginteraction",
            name="medicine_b",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions_as_b",
                to="prescriptions.medicine",
            ),
        ),
        migrations.AddIndex(
            model_name="druginteraction",
            index=models.Index(
                fields=["medicine_a", "medicine_b"],
                name="prescriptio_medicin_130c8a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="druginteraction",
            unique_together={("medicine_a", "medicine_b")},
        ),
    ]
