# Generated by Django 4.2.30 on 2026-09-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="gst_rate",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name="medicine",
            name="hsn_code",
            field=models.CharField(default="3004", max_length=10),
        ),
    ]
