'use client';

import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { ArrowUpCircle, Bell, Check, CheckCheck, ChevronDown, Loader2, MapPin } from 'lucide-react';
import { withAuth } from '@/components/auth/withAuth';
import { api } from '@/lib/api';
import { EmptyState, ErrorState, PageHeader, SkeletonRows, StatusPill, severityTone } from '@/components/ui/page';
import { cn } from '@/lib/utils';
import { t, intlLocale } from '@/lib/i18n';

const STATUSES = [
  { k: 'active', get l() { return t("Active"); } },
  { k: 'acknowledged', get l() { return t("Acknowledged"); } },
  { k: 'resolved', get l() { return t("Resolved"); } },
  { k: 'false_positive', get l() { return t("False positive"); } },
  { k: '', get l() { return t("All"); } },
];
const SEVERITIES = ['', 'critical', 'high', 'medium', 'low'];
const fmt = (iso?: string | null) => (iso ? new Date(iso).toLocaleString(intlLocale(), { day: 'numeric', month: 'short', year: 'numeric', hour: 'numeric', minute: '2-digit' }) : '—');

function AlertsPage() {
  const qc = useQueryClient();
  const [status, setStatus] = useState('active');
  const [severity, setSeverity] = useState('');
  const [open, setOpen] = useState<string | null>(null);

  const q = useQuery<any>({
    queryKey: ['surv-alerts', status, severity],
    queryFn: () => api.surveillance.getAlerts({ ...(status ? { status } : {}), ...(severity ? { severity } : {}) }),
  });

  const act = useMutation({
    mutationFn: ({ id, action }: { id: string; action: 'acknowledge' | 'escalate' | 'resolve' }) =>
      action === 'acknowledge' ? api.surveillance.acknowledgeAlert(id) : action === 'escalate' ? api.surveillance.escalateAlert(id) : api.surveillance.resolveAlert(id),
    onSuccess: (_d, v) => {
      toast.success(v.action === 'acknowledge' ? t("Alert acknowledged") : v.action === 'escalate' ? t("Alert escalated") : t("Alert resolved"));
      qc.invalidateQueries({ queryKey: ['surv-alerts'] });
      qc.invalidateQueries({ queryKey: ['surv-overview'] });
      qc.invalidateQueries({ queryKey: ['shell', 'surveillance-alerts'] });
    },
  });

  const list = q.data?.results ?? [];

  return (
    <div>
      <PageHeader title={t("Outbreak alerts")} description={t("Generated by the surveillance pipeline when clusters, anomalies or forecasts cross thresholds. Acknowledge, escalate to district officers, or resolve.")} />
      <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="inline-flex flex-wrap rounded-[10px] border bg-card p-1 shadow-sm">
          {STATUSES.map((s) => (
            <button key={s.k} onClick={() => setStatus(s.k)} className={cn('rounded-lg px-3 py-1.5 text-[13px] font-medium transition-colors', status === s.k ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground')}>{s.l}</button>
          ))}
        </div>
        <select value={severity} onChange={(e) => setSeverity(e.target.value)} className="h-10 rounded-[10px] border bg-card px-3 text-[13.5px] shadow-sm" aria-label={t("Severity")}>
          {SEVERITIES.map((s) => <option key={s} value={s}>{s ? s[0].toUpperCase() + s.slice(1) : t("All severities")}</option>)}
        </select>
      </div>

      {q.isLoading ? (
        <div className="rounded-2xl border bg-card p-5"><SkeletonRows rows={5} /></div>
      ) : q.isError ? (
        <ErrorState onRetry={() => q.refetch()} />
      ) : !list.length ? (
        <EmptyState icon={Bell} title={t("No alerts in this view")} />
      ) : (
        <ul className="space-y-3">
          {list.map((a: any) => {
            const isOpen = open === a.id;
            const busy = act.isPending && act.variables?.id === a.id;
            return (
              <li key={a.id} className="overflow-hidden rounded-2xl border bg-card shadow-sm">
                <button onClick={() => setOpen(isOpen ? null : a.id)} className="flex w-full items-start gap-4 px-5 py-4 text-left hover:bg-muted/30" aria-expanded={isOpen}>
                  <span className={cn('mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full', a.severity === 'critical' || a.severity === 'high' ? 'bg-destructive' : a.severity === 'medium' ? 'bg-warning' : 'bg-info')} />
                  <span className="min-w-0 flex-1">
                    <span className="block text-[15px] font-semibold">{a.title}</span>
                    <span className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-[12.5px] text-muted-foreground">
                      <span>{t(a.disease_name)} ({a.disease_code})</span>
                      <span className="inline-flex items-center gap-1"><MapPin className="h-3 w-3" />{(a.affected_regions_data || []).map((r: any) => r.name).join(', ') || '—'}</span>
                      <span>{fmt(a.generated_at)}</span>
                    </span>
                  </span>
                  <span className="flex shrink-0 flex-col items-end gap-1.5">
                    <StatusPill tone={severityTone(a.severity)}>{t(a.severity_display)}</StatusPill>
                    <span className="text-[11.5px] text-muted-foreground">{t(a.status_display)}{a.escalation_level ? t(" · level {escalation_level}", { escalation_level: a.escalation_level }) : ''}</span>
                  </span>
                  <ChevronDown className={cn('mt-1 h-4 w-4 shrink-0 text-muted-foreground transition-transform', isOpen && 'rotate-180')} />
                </button>
                {isOpen && (
                  <div className="space-y-4 border-t px-5 py-4 text-[13.5px]">
                    <p className="leading-relaxed">{a.description}</p>
                    {a.predicted_impact && <div><div className="kicker mb-1">{t("Predicted impact")}</div><p className="text-muted-foreground">{a.predicted_impact}</p></div>}
                    {a.recommended_actions && (
                      <div>
                        <div className="kicker mb-1">{t("Recommended actions")}</div>
                        {Array.isArray(a.recommended_actions) ? (
                          <ul className="list-disc space-y-1 pl-5 text-muted-foreground">{a.recommended_actions.map((r: string, i: number) => <li key={i}>{r}</li>)}</ul>
                        ) : (
                          <ul className="list-disc space-y-1 pl-5 text-muted-foreground">{String(a.recommended_actions).split(/\n|;\s*/).filter(Boolean).map((r, i) => <li key={i}>{r.replace(/^[-•\d.\s]+/, '')}</li>)}</ul>
                        )}
                      </div>
                    )}
                    <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                      {a.confidence != null && <span>{t("Model confidence {round}%", { round: Math.round(a.confidence * 100) })}</span>}
                      {a.acknowledged_at && <span>{t("· Acknowledged {fmt}", { fmt: fmt(a.acknowledged_at) })}</span>}
                      {a.resolved_at && <span>{t("· Resolved {fmt}", { fmt: fmt(a.resolved_at) })}</span>}
                    </div>
                    {!['resolved', 'false_positive'].includes(a.status) && (
                      <div className="flex flex-wrap gap-2 border-t pt-4">
                        {a.status === 'active' && (
                          <button onClick={() => act.mutate({ id: a.id, action: 'acknowledge' })} disabled={busy} className="inline-flex h-9 items-center gap-1.5 rounded-[10px] border px-3.5 text-[13px] font-medium hover:bg-muted disabled:opacity-60"><Check className="h-4 w-4" />{' '}{t("Acknowledge")}</button>
                        )}
                        {(a.escalation_level ?? 0) < 3 && (
                          <button onClick={() => act.mutate({ id: a.id, action: 'escalate' })} disabled={busy} className="inline-flex h-9 items-center gap-1.5 rounded-[10px] border border-warning/40 px-3.5 text-[13px] font-medium text-warning hover:bg-warning/5 disabled:opacity-60"><ArrowUpCircle className="h-4 w-4" />{' '}{a.escalation_level ? t("Escalate (level {level})", { level: a.escalation_level + 1 }) : t("Escalate")}</button>
                        )}
                        <button onClick={() => act.mutate({ id: a.id, action: 'resolve' })} disabled={busy} className="ml-auto inline-flex h-9 items-center gap-1.5 rounded-[10px] bg-primary px-3.5 text-[13px] font-medium text-primary-foreground shadow-button disabled:opacity-60">
                          {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCheck className="h-4 w-4" />}{' '}{t("Resolve")}</button>
                      </div>
                    )}
                  </div>
                )}
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}

export default withAuth(AlertsPage, ['admin', 'authority']);
