# Generated by Django 4.2.28 on 2026-02-10 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prescriptions", "0001_initial"),
        ("adherence", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doseschedule",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="prescriptions.medicine"
            ),
        ),
        migrations.AddField(
            model_name="doseschedule",
            name="prescription_medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="prescriptions.prescriptionmedicine",
            ),
        ),
        migrations.AddField(
            model_name="doseschedule",
            name="tracker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dose_schedules",
                to="adherence.adherencetracker",
            ),
        ),
        migrations.AddField(
            model_name="adherencetracker",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adherence_trackers",
                to="patients.profile",
            ),
        ),
        migrations.AddField(
            model_name="adherencetracker",
            name="prescription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adherence_tracker",
                to="prescriptions.prescription",
            ),
        ),
        migrations.AddField(
            model_name="adherencereminder",
            name="dose_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="adherence.doseschedule",
            ),
        ),
        migrations.AddField(
            model_name="adherencereminder",
            name="tracker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="adherence.adherencetracker",
            ),
        ),
        migrations.AddIndex(
            model_name="doseschedule",
            index=models.Index(
                fields=["tracker", "scheduled_time"],
                name="dose_schedu_tracker_5d9689_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doseschedule",
            index=models.Index(
                fields=["scheduled_time", "is_taken"],
                name="dose_schedu_schedul_f810de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adherencetracker",
            index=models.Index(
                fields=["patient", "is_active"], name="adherence_t_patient_a77548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adherencetracker",
            index=models.Index(
                fields=["start_date", "end_date"], name="adherence_t_start_d_064561_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adherencereminder",
            index=models.Index(
                fields=["tracker", "status"], name="adherence_r_tracker_9e5485_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adherencereminder",
            index=models.Index(
                fields=["sent_at"], name="adherence_r_sent_at_551b60_idx"
            ),
        ),
    ]
