# Generated by Django 4.2.28 on 2026-02-14 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('abnormal_labs', 'Abnormal Lab Results'), ('low_adherence', 'Low Medication Adherence'), ('high_risk', 'Elevated Risk Score')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Alert',
                'verbose_name_plural': 'Dashboard Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_dismissed', '-created_at'], name='dashboard_d_patient_7f38ed_idx'), models.Index(fields=['patient', 'is_read'], name='dashboard_d_patient_8f84ff_idx')],
            },
        ),
    ]
