# Generated by Django 4.2.28 on 2026-02-14 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('medical_record', 'Medical Record'), ('prescription', 'Prescription'), ('lab_report', 'Lab Report'), ('visit_attachment', 'Visit Attachment'), ('bulk', 'Bulk Download')], max_length=30)),
                ('file_id', models.PositiveIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download Log',
                'verbose_name_plural': 'Download Logs',
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['user', '-downloaded_at'], name='dashboard_d_user_id_83bf2f_idx')],
            },
        ),
    ]
