# Generated by Django 4.2.29 on 2026-03-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0003_real_time_inference_queue"),
        ("dashboard", "0002_downloadlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardalert",
            name="surveillance_alert",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the surveillance alert that triggered this dashboard alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboard_alerts",
                to="surveillance.alert",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("abnormal_labs", "Abnormal Lab Results"),
                    ("low_adherence", "Low Medication Adherence"),
                    ("high_risk", "Elevated Risk Score"),
                    ("outbreak", "Disease Outbreak in Region"),
                ],
                max_length=30,
            ),
        ),
    ]
