# Generated by Django 4.2.30 on 2026-09-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_remove_profile_emergency_contact_number_and_more"),
        ("dashboard", "0003_add_outbreak_alert_type_and_surveillance_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardalert",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific family-member profile this alert belongs to (see medical.PatientVisitRecord.profile).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_alerts",
                to="patients.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardalert",
            index=models.Index(
                fields=["profile", "is_dismissed", "-created_at"],
                name="dashboard_d_profile_0c5d61_idx",
            ),
        ),
    ]
