# Generated by Django 4.2.30 on 2026-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_backfill_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadlog",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("medical_record", "Medical Record"),
                    ("prescription", "Prescription"),
                    ("lab_report", "Lab Report"),
                    ("visit_attachment", "Visit Attachment"),
                    ("invoice", "Invoice"),
                    ("health_card", "Health Card"),
                    ("bulk", "Bulk Download"),
                ],
                max_length=30,
            ),
        ),
    ]
