# Generated by Django 4.2.28 on 2026-02-10 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorPatientAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("access_method", models.CharField(default="qr_scan", max_length=50)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_accesses",
                        to="patients.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "patient", "expires_at"],
                        name="medical_doc_doctor__74b772_idx",
                    )
                ],
            },
        ),
    ]
