# Generated by Django 4.2.28 on 2026-02-14 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0002_doctorpatientaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('diagnosis', models.TextField()),
                ('tests_performed', models.TextField()),
                ('prescription', models.TextField()),
                ('visit_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Visit Record',
                'verbose_name_plural': 'Patient Visit Records',
                'ordering': ['-visit_date'],
            },
        ),
    ]
