# Generated by Django 4.2.28 on 2026-02-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_patientvisitrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisitrecord',
            name='doctor_notes',
            field=models.TextField(blank=True, help_text='Important notes from the doctor'),
        ),
        migrations.CreateModel(
            name='VisitReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='visit_reports/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_attachments', to='medical.patientvisitrecord')),
            ],
            options={
                'verbose_name': 'Visit Report Attachment',
                'verbose_name_plural': 'Visit Report Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
