# Generated by Django 4.2.28 on 2026-02-14 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0004_patientvisitrecord_doctor_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(db_index=True, max_length=255)),
                ('value', models.FloatField(help_text='Numeric result value')),
                ('unit', models.CharField(help_text='e.g. mg/dL, mmol/L, %', max_length=50)),
                ('normal_min', models.FloatField(help_text='Lower bound of normal range')),
                ('normal_max', models.FloatField(help_text='Upper bound of normal range')),
                ('report_file', models.FileField(blank=True, help_text='PDF or image of the lab report', upload_to='lab_reports/%Y/%m/')),
                ('tested_at', models.DateTimeField(help_text='When the test was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_results', to=settings.AUTH_USER_MODEL)),
                ('visit_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='medical.patientvisitrecord')),
            ],
            options={
                'verbose_name': 'Lab Test Result',
                'verbose_name_plural': 'Lab Test Results',
                'ordering': ['-tested_at'],
                'indexes': [models.Index(fields=['patient', 'test_name', '-tested_at'], name='medical_lab_patient_c3d219_idx')],
            },
        ),
    ]
