# Generated by Django 4.2.28 on 2026-02-14 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0005_labtestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('blood_pressure', 'Blood Pressure'), ('sugar', 'Blood Sugar'), ('weight', 'Weight'), ('bmi', 'BMI')], db_index=True, max_length=20)),
                ('value', models.FloatField(help_text='Primary value (systolic for BP)')),
                ('secondary_value', models.FloatField(blank=True, help_text='Diastolic for BP; unused for other metrics', null=True)),
                ('unit', models.CharField(help_text='mmHg, mg/dL, kg, kg/m²', max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='When the measurement was taken')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Metric',
                'verbose_name_plural': 'Health Metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'metric_type', '-recorded_at'], name='medical_hea_patient_e98534_idx')],
            },
        ),
    ]
