# Generated by Django 4.2.28 on 2026-02-18 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0006_healthmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreportattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Doctor who uploaded this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
