# Generated by Django 4.2.30 on 2026-09-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_remove_profile_emergency_contact_number_and_more"),
        ("medical", "0008_add_added_by_to_allergy_and_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthmetric",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific family-member profile this metric belongs to (see PatientVisitRecord.profile).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_metrics",
                to="patients.profile",
            ),
        ),
        migrations.AddField(
            model_name="labtestresult",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific family-member profile this result belongs to (see PatientVisitRecord.profile).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_test_results",
                to="patients.profile",
            ),
        ),
        migrations.AddField(
            model_name="patientvisitrecord",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific family-member profile this visit belongs to. Nullable for backward compatibility with rows predating this field (backfilled via migration) — new code should always set this.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_records",
                to="patients.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="healthmetric",
            index=models.Index(
                fields=["profile", "metric_type", "-recorded_at"],
                name="medical_hea_profile_e2aeab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="labtestresult",
            index=models.Index(
                fields=["profile", "test_name", "-tested_at"],
                name="medical_lab_profile_248279_idx",
            ),
        ),
    ]
