# Generated by Django 4.2.28 on 2026-02-13 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alert_type", models.CharField(max_length=50)),
                ("disease_code", models.CharField(max_length=10)),
                ("disease_name", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("predicted_impact", models.TextField(blank=True)),
                ("contributing_factors", models.JSONField(default=dict)),
                ("recommended_actions", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("escalation_level", models.IntegerField(default=1)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-generated_at", "-severity"],
            },
        ),
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("disease_code", models.CharField(max_length=10)),
                ("disease_name", models.CharField(max_length=255)),
                ("detection_date", models.DateField()),
                ("anomaly_score", models.FloatField()),
                ("actual_cases", models.IntegerField()),
                ("expected_cases", models.FloatField()),
                ("deviation_percentage", models.FloatField()),
                ("description", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-detection_date", "-anomaly_score"],
            },
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("disease_code", models.CharField(max_length=10)),
                ("disease_name", models.CharField(max_length=255)),
                ("detection_date", models.DateField()),
                ("centroid_lat", models.FloatField()),
                ("centroid_lon", models.FloatField()),
                ("radius_km", models.FloatField()),
                ("total_cases", models.IntegerField()),
                ("total_population", models.IntegerField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("growth_rate", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-detection_date", "-severity"],
            },
        ),
        migrations.CreateModel(
            name="ClusterRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("surveillance", "Disease Surveillance"),
                            ("research", "Research"),
                            ("data_sharing", "Data Sharing"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_granted", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("signature_data", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnvironmentalData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("rainfall", models.FloatField(blank=True, null=True)),
                ("aqi", models.IntegerField(blank=True, null=True)),
                ("pm25", models.FloatField(blank=True, null=True)),
                ("pm10", models.FloatField(blank=True, null=True)),
                ("water_quality_index", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "region"],
            },
        ),
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("disease_code", models.CharField(max_length=10)),
                ("disease_name", models.CharField(max_length=255)),
                ("forecast_date", models.DateField()),
                ("prediction_date", models.DateField()),
                (
                    "horizon_days",
                    models.IntegerField(
                        choices=[(7, "7 days"), (14, "14 days"), (30, "30 days")]
                    ),
                ),
                ("predicted_cases", models.FloatField()),
                ("lower_bound", models.FloatField()),
                ("upper_bound", models.FloatField()),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-forecast_date", "prediction_date"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("dashboard", "Dashboard"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("district", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(default="India", max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("population", models.IntegerField()),
                ("hospital_count", models.IntegerField(default=0)),
                ("sanitation_index", models.FloatField(default=50.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["state", "district", "name"],
            },
        ),
        migrations.CreateModel(
            name="SurveillanceData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("disease_code", models.CharField(max_length=10)),
                ("disease_name", models.CharField(max_length=255)),
                ("case_count", models.IntegerField()),
                ("average_severity", models.FloatField()),
                ("cases_per_100k", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveillance_data",
                        to="surveillance.region",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "region"],
            },
        ),
        migrations.CreateModel(
            name="RiskScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("disease_code", models.CharField(max_length=10)),
                ("disease_name", models.CharField(max_length=255)),
                ("calculation_date", models.DateField()),
                (
                    "risk_level",
                    models.IntegerField(
                        choices=[
                            (0, "Low"),
                            (1, "Medium"),
                            (2, "High"),
                            (3, "Critical"),
                        ]
                    ),
                ),
                ("risk_probability", models.FloatField()),
                ("contributing_factors", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_scores",
                        to="surveillance.region",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculation_date", "-risk_level"],
            },
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                fields=["state", "district"], name="surveillanc_state_92c82d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                fields=["latitude", "longitude"], name="surveillanc_latitud_dd613d_idx"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="alert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="surveillance.alert",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="forecast",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="surveillance.region",
            ),
        ),
        migrations.AddField(
            model_name="environmentaldata",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environmental_data",
                to="surveillance.region",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to="patients.profile",
            ),
        ),
        migrations.AddField(
            model_name="clusterregion",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="surveillance.cluster",
            ),
        ),
        migrations.AddField(
            model_name="clusterregion",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveillance.region"
            ),
        ),
        migrations.AddIndex(
            model_name="cluster",
            index=models.Index(
                fields=["disease_code", "detection_date", "is_active"],
                name="surveillanc_disease_1b0921_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cluster",
            index=models.Index(
                fields=["severity", "is_active"], name="surveillanc_severit_b2a5f1_idx"
            ),
        ),
        migrations.AddField(
            model_name="anomaly",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomalies",
                to="surveillance.region",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="affected_regions",
            field=models.ManyToManyField(
                related_name="alerts", to="surveillance.region"
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="surveillancedata",
            index=models.Index(
                fields=["date", "region", "disease_code"],
                name="surveillanc_date_a1ff06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="surveillancedata",
            index=models.Index(
                fields=["disease_code", "date"], name="surveillanc_disease_f91d92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveillancedata",
            index=models.Index(
                fields=["region", "date"], name="surveillanc_region__299abe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="surveillancedata",
            unique_together={("date", "region", "disease_code")},
        ),
        migrations.AddIndex(
            model_name="riskscore",
            index=models.Index(
                fields=["disease_code", "calculation_date"],
                name="surveillanc_disease_5b3a85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskscore",
            index=models.Index(
                fields=["risk_level", "calculation_date"],
                name="surveillanc_risk_le_e35f31_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="riskscore",
            unique_together={("region", "disease_code", "calculation_date")},
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["alert", "status"], name="surveillanc_alert_i_469dbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "status"], name="surveillanc_recipie_c65659_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(
                fields=["region", "disease_code", "forecast_date"],
                name="surveillanc_region__100039_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(
                fields=["prediction_date"], name="surveillanc_predict_f24948_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="environmentaldata",
            index=models.Index(
                fields=["region", "date"], name="surveillanc_region__7135a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="environmentaldata",
            index=models.Index(fields=["date"], name="surveillanc_date_d60f5f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="environmentaldata",
            unique_together={("region", "date")},
        ),
        migrations.AddIndex(
            model_name="consent",
            index=models.Index(
                fields=["profile", "consent_type", "is_granted"],
                name="surveillanc_profile_2680dc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="consent",
            unique_together={("profile", "consent_type")},
        ),
        migrations.AlterUniqueTogether(
            name="clusterregion",
            unique_together={("cluster", "region")},
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(
                fields=["disease_code", "detection_date", "is_resolved"],
                name="surveillanc_disease_b2e1d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(
                fields=["region", "detection_date"],
                name="surveillanc_region__6c5d64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "severity", "-generated_at"],
                name="surveillanc_status_e87e6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["disease_code", "status"], name="surveillanc_disease_2b52cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["generated_at"], name="surveillanc_generat_4fac8d_idx"
            ),
        ),
    ]
