# Generated by Django 4.2.28 on 2026-02-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="horizon_days",
            field=models.IntegerField(
                choices=[
                    (7, "7 days"),
                    (14, "14 days"),
                    (30, "30 days"),
                    (60, "60 days"),
                    (90, "90 days"),
                ]
            ),
        ),
    ]
