# Generated by Django 4.2.29 on 2026-03-11 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0002_alter_forecast_horizon_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingInferenceQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("disease_code", models.CharField(max_length=10)),
                ("severity", models.PositiveSmallIntegerField(default=1)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_inferences",
                        to="surveillance.region",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["region", "disease_code"],
                        name="surveillanc_region__ef61ff_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="surveillanc_recorde_24aa66_idx"
                    ),
                ],
            },
        ),
    ]
