# Generated by Django 4.2.30 on 2026-10-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0010_backfill_profile"),
        ("surveillance", "0003_real_time_inference_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomaly",
            name="data_cutoff",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="anomaly",
            name="model_version",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="anomaly",
            name="provenance",
            field=models.CharField(default="legacy", max_length=30),
        ),
        migrations.AddField(
            model_name="forecast",
            name="data_cutoff",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="model_version",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="forecast",
            name="provenance",
            field=models.CharField(default="legacy", max_length=30),
        ),
        migrations.AddField(
            model_name="pendinginferencequeue",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendinginferencequeue",
            name="diagnosis",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_inference",
                to="medical.diagnosis",
            ),
        ),
        migrations.AddField(
            model_name="pendinginferencequeue",
            name="occurrence_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="area_sq_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riskscore",
            name="data_cutoff",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riskscore",
            name="inference_status",
            field=models.CharField(default="legacy", max_length=20),
        ),
        migrations.AddField(
            model_name="riskscore",
            name="model_version",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="riskscore",
            name="provenance",
            field=models.CharField(default="legacy", max_length=30),
        ),
        migrations.AddField(
            model_name="surveillancedata",
            name="observation_status",
            field=models.CharField(default="observed", max_length=20),
        ),
        migrations.AddField(
            model_name="surveillancedata",
            name="provenance",
            field=models.CharField(default="legacy", max_length=30),
        ),
        migrations.AlterField(
            model_name="alert",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="riskscore",
            name="risk_level",
            field=models.IntegerField(
                choices=[
                    (-1, "Unavailable"),
                    (0, "Low"),
                    (1, "Medium"),
                    (2, "High"),
                    (3, "Critical"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="riskscore",
            name="risk_probability",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
