# Generated by Django 4.2.30 on 2026-10-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0005_safe_inference_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="model_version",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="cluster",
            name="provenance",
            field=models.CharField(default="legacy", max_length=30),
        ),
    ]
