# Generated by Django 4.2.28 on 2026-02-10 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prescriptions", "0001_initial"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispensingrecord",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispensing_records",
                to="prescriptions.prescription",
            ),
        ),
        migrations.AddField(
            model_name="dispensingrecord",
            name="prescription_medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispensing_records",
                to="prescriptions.prescriptionmedicine",
            ),
        ),
    ]
