# Generated by Django 4.2.28 on 2026-02-19 11:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
        ("pharmacy", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_in_stock", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=10)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_inventory",
                        to="prescriptions.medicine",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="pharmacy.pharmacy",
                    ),
                ),
            ],
            options={
                "ordering": ["medicine__name"],
                "indexes": [
                    models.Index(
                        fields=["pharmacy", "medicine"],
                        name="pharmacy_ph_pharmac_27b137_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="pharmacy_ph_expiry__5ec868_idx"
                    ),
                ],
            },
        ),
    ]
