# Generated by Django 4.2.29 on 2026-03-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0003_pharmacyinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="district",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name="pharmacy",
            index=models.Index(
                fields=["district"], name="pharmacy_ph_distric_19736b_idx"
            ),
        ),
    ]
