# Generated by Django 4.2.29 on 2026-03-12 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0004_pharmacy_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispensingrecord",
            name="pharmacy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispensing_records",
                to="pharmacy.pharmacy",
            ),
        ),
    ]
