# Generated by Django 4.2.30 on 2026-09-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0006_dispensing_prices_and_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispensingrecord",
            name="gst_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="dispensingrecord",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="dispensingrecord",
            name="tax_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="dispensingrecord",
            name="taxable_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cgst",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sgst",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="taxable_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="gstin",
            field=models.CharField(
                blank=True,
                help_text="GST identification number, printed on invoices",
                max_length=15,
            ),
        ),
    ]
